# CJ Aurum -- Aurum Creative
# July 29, 2021 
# Coin Toss for PyQt5

from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Coin Toss")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.num_flips_label = QtWidgets.QLabel(self.centralwidget)
        self.num_flips_label.setGeometry(QtCore.QRect(190, 10, 220, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_flips_label.sizePolicy().hasHeightForWidth())
        self.num_flips_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num_flips_label.setFont(font)
        self.num_flips_label.setObjectName("num_flips_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(75, 140, 450, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.tails_label_answer = QtWidgets.QLabel(self.frame)
        self.tails_label_answer.setGeometry(QtCore.QRect(250, 10, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tails_label_answer.sizePolicy().hasHeightForWidth())
        self.tails_label_answer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tails_label_answer.setFont(font)
        self.tails_label_answer.setFrameShape(QtWidgets.QFrame.Panel)
        self.tails_label_answer.setText("")
        self.tails_label_answer.setAlignment(QtCore.Qt.AlignCenter)
        self.tails_label_answer.setObjectName("tails_label_answer")
        self.tails_label = QtWidgets.QLabel(self.frame)
        self.tails_label.setGeometry(QtCore.QRect(120, 10, 61, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tails_label.sizePolicy().hasHeightForWidth())
        self.tails_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.tails_label.setFont(font)
        self.tails_label.setObjectName("tails_label")
        self.heads_label = QtWidgets.QLabel(self.frame)
        self.heads_label.setGeometry(QtCore.QRect(120, 50, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heads_label.sizePolicy().hasHeightForWidth())
        self.heads_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.heads_label.setFont(font)
        self.heads_label.setObjectName("heads_label")
        self.heads_label_answer = QtWidgets.QLabel(self.frame)
        self.heads_label_answer.setGeometry(QtCore.QRect(250, 50, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heads_label_answer.sizePolicy().hasHeightForWidth())
        self.heads_label_answer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.heads_label_answer.setFont(font)
        self.heads_label_answer.setFrameShape(QtWidgets.QFrame.Panel)
        self.heads_label_answer.setText("")
        self.heads_label_answer.setAlignment(QtCore.Qt.AlignCenter)
        self.heads_label_answer.setObjectName("heads_label_answer")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.flip_it())
        self.pushButton.setGeometry(QtCore.QRect(260, 90, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.head_label_image = QtWidgets.QLabel(self.centralwidget)
        self.head_label_image.setGeometry(QtCore.QRect(40, 30, 80, 80))
        self.head_label_image.setText("")
        self.head_label_image.setPixmap(QtGui.QPixmap("../GitHub/Images/Heads.png"))
        self.head_label_image.setScaledContents(True)
        self.head_label_image.setObjectName("head_label_image")
        self.head_label_image_2 = QtWidgets.QLabel(self.centralwidget)
        self.head_label_image_2.setGeometry(QtCore.QRect(480, 30, 80, 80))
        self.head_label_image_2.setText("")
        self.head_label_image_2.setPixmap(QtGui.QPixmap("../GitHub/Images/Tails.png"))
        self.head_label_image_2.setScaledContents(True)
        self.head_label_image_2.setObjectName("head_label_image_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.num_flips_label.setText(_translate("MainWindow", "Flip the coin how many times?"))
        self.tails_label.setText(_translate("MainWindow", "Tails:"))
        self.heads_label.setText(_translate("MainWindow", "Heads:"))
        self.pushButton.setText(_translate("MainWindow", "Flip It!!"))

    def flip_it(self):
        heads = 0
        tails = 0

        for i in range(int(self.lineEdit.text())):
            result = random.randint(0, 1)

            if result == 0:
                heads += 1
            else:
                tails += 1

        self.tails_label_answer.setText(str(tails))
        self.heads_label_answer.setText(str(heads))
        self.lineEdit.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
